# Exploring the pytorch library

### Tensors, tensor operations

In [2]:
import torch
torch.empty(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
torch.rand(5, 3)

tensor([[0.1286, 0.0805, 0.0955],
        [0.1075, 0.6185, 0.2925],
        [0.9540, 0.7273, 0.2993],
        [0.2680, 0.6935, 0.6790],
        [0.0616, 0.9199, 0.2829]])

In [4]:
torch.zeros(5, 3, dtype=torch.double)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [5]:
x = torch.randn(4, 4)
x.size()

torch.Size([4, 4])

In [6]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [7]:
y = torch.randn(4, 4)

x + y

tensor([[ 0.7405,  1.9454,  0.7123,  2.3541],
        [-0.4449,  0.4252, -0.1576, -1.0881],
        [-0.3790,  0.4123,  1.2227, -0.9817],
        [ 2.0954, -2.1478,  1.4654,  2.5361]])

In [8]:
x * y

tensor([[-1.1747,  0.1061,  0.1259,  1.3802],
        [-0.1377,  0.0313, -0.1546,  0.1225],
        [-2.1891, -0.6041,  0.0593,  0.0664],
        [ 1.0926, -0.9303, -1.1659,  1.5880]])

In [10]:
y[:, 1]

tensor([1.8892, 0.0946, 1.0102, 0.3696])

In [11]:
x.view(16)

tensor([-0.7751,  0.0562,  0.3863,  1.1049, -0.6551,  0.3306,  0.3222, -0.9606,
         1.3021, -0.5979,  0.0506, -0.9087,  1.1193, -2.5173,  2.0376,  1.1269])

In [12]:
x.view(-1, 8)

tensor([[-0.7751,  0.0562,  0.3863,  1.1049, -0.6551,  0.3306,  0.3222, -0.9606],
        [ 1.3021, -0.5979,  0.0506, -0.9087,  1.1193, -2.5173,  2.0376,  1.1269]])

Numpy: cpu warning

In [15]:
import numpy as np

ones_t = torch.ones(5)
b = ones_t.numpy()
ones_t

tensor([1., 1., 1., 1., 1.])

In [17]:
b += 2
ones_t # CPU TENSORS SHARE MEMORY WITH THEIR NUMPY COUNTERPARTS

tensor([3., 3., 3., 3., 3.])

### Autograd

In [ ]:
x = torch.randn(3, requires_grad=True)