# Exploring the pytorch library

### Tensors, tensor operations

In [1]:
import torch
torch.empty(5, 3)

tensor([[1.6078e+19, 4.4721e+21, 5.0789e-11],
        [4.4721e+21, 1.0986e+27, 7.1854e+22],
        [3.0573e+32, 1.8469e+25, 5.1931e-11],
        [7.0367e+22, 2.4032e+20, 1.6928e+22],
        [2.7945e+20, 2.2419e+20, 3.2532e+33]])

In [2]:
torch.rand(5, 3)

tensor([[0.0127, 0.9181, 0.8654],
        [0.1903, 0.8878, 0.4193],
        [0.3859, 0.4467, 0.1064],
        [0.2397, 0.9158, 0.1724],
        [0.3214, 0.3033, 0.7756]])

In [3]:
torch.zeros(5, 3, dtype=torch.double)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [4]:
x = torch.randn(4, 4)
x.size()

torch.Size([4, 4])

In [5]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [6]:
y = torch.randn(4, 4)

x + y

tensor([[ 2.0883, -0.6894, -1.5013, -0.9400],
        [ 0.4966,  0.6295,  1.4388,  1.5048],
        [-3.3060,  1.0870,  0.7773,  1.9012],
        [ 0.9976, -1.9233,  0.3605,  0.0481]])

In [7]:
x * y

tensor([[ 0.6014, -0.9474,  0.4555, -0.0792],
        [ 0.0274, -2.4267,  0.5174,  0.2802],
        [ 1.8756,  0.1650, -0.5181,  0.1612],
        [ 0.2469,  0.9225, -0.1028, -0.1034]])

In [8]:
y[:, 1]

tensor([-1.3773,  1.9040,  0.9047, -0.9141])

In [9]:
x.view(16)

tensor([ 0.3450,  0.6879, -1.0793,  0.0779,  0.0633, -1.2745,  0.7314,  0.2177,
        -0.7273,  0.1824,  1.2066,  1.8122,  0.5428, -1.0091, -0.1875,  0.3465])

In [10]:
x.view(-1, 8)

tensor([[ 0.3450,  0.6879, -1.0793,  0.0779,  0.0633, -1.2745,  0.7314,  0.2177],
        [-0.7273,  0.1824,  1.2066,  1.8122,  0.5428, -1.0091, -0.1875,  0.3465]])

Numpy: cpu warning

In [11]:
import numpy as np

ones_t = torch.ones(5)
b = ones_t.numpy()
ones_t

tensor([1., 1., 1., 1., 1.])

In [12]:
b += 2
ones_t # CPU TENSORS SHARE MEMORY WITH THEIR NUMPY COUNTERPARTS

tensor([3., 3., 3., 3., 3.])

### Autograd

In [13]:
x = torch.randn(3, requires_grad=True)
y = x + 2
y

tensor([1.8842, 0.8440, 2.3632], grad_fn=<AddBackward0>)

In [14]:
z = y.mean()
z

tensor(1.6972, grad_fn=<MeanBackward0>)

In [15]:
z.backward()
x.grad

tensor([0.3333, 0.3333, 0.3333])

In [16]:
y.backward(torch.ones(3))

In [17]:
x.grad

tensor([1.3333, 1.3333, 1.3333])

### Backpropagation

In [19]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# 1. Forward pass
y_hat = x * w
loss = (y_hat - y) ** 2

# 2. Backward pass
loss.backward()

w.grad

tensor(-2.)

### Gradient descent

In [20]:
# generating data with best fit of 2x
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
y = np.array([2, 4, 6, 8, 10], dtype=np.float32)

a = .0

def forward(x):
    return a * x

def loss(y, y_pred):
    return ((y_pred - y) ** 2).mean()

$$ loss = \frac {(ax - y)^2} {n} = \frac {a^2x^2 - 2yax + y^2} {n} $$

$$ \frac {d(loss)} {da} = \frac {2ax^2} $$